name: Draft Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  draft-release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish RatScanner/RatScanner.csproj -c Release -o publish -p:PublishSingleFile=true --runtime win-x64 --self-contained
    - name: Include Data
      run: |
        curl -L "https://github.com/RatScanner/RatScannerData/releases/latest/download/Data.zip" --output "publish/Data.zip"
        7z x publish/Data.zip -opublish/Data
        Remove-Item publish/Data.zip
    - name: Include Updater
      run: curl -L "https://github.com/RatScanner/RatUpdater/releases/latest/download/RatUpdater.exe" --output "publish/RatUpdater.exe"
    - name: Zip Content
      run: 7z a -r RatScanner.zip publish/*
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      with:
        files: RatScanner.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
